---
- name: Check if config file exists
  become: true
  stat:
    path: "{{ zsh_config_path }}"
  register: _zsh_config_file_check

- name: Ensure dependencies are installed
  become: true
  package:
    state: present
    name:
      - zsh
      - git
      - curl
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5

- name: Delete old version
  become: true
  file:
    path: "/home/{{ zsh_user }}/.oh-my-zsh"
    state: absent

- name: Execute the installer
  become: true
  become_user: "{{ zsh_user }}"
  shell: sh -c "$(curl -fsSL {{ zsh_installer_url }})" "" --unattended --keep-zshrc
  changed_when: false

- name: Fix completions ownership
  become: true
  file:
    path: "/home/{{ zsh_user }}/.oh-my-zsh/cache/completions"
    state: directory
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    mode: "0755"

- name: Change shell
  become: true
  user:
    name: "{{ zsh_user }}"
    shell: "/usr/bin/zsh"

- include_tasks: plugins.yml

- include_tasks: powerlevel10k.yml
  when: zsh_set_powerlevel10k_theme | bool

- name: Create zsh-config using template
  become: true
  template:
    src: "zsh-config.j2"
    dest: "{{ zsh_config_path }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    mode: "0640"
  when: not _zsh_config_file_check.stat.exists or
    zsh_force_replace_zsh_config | bool
