- name: Download zsh-syntax-highlighting plugin
  become: true
  become_user: "{{ zsh_user }}"
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "/home/{{ zsh_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: "master"
    clone: true

- name: Download zsh-autosuggestions plugin
  become: true
  become_user: "{{ zsh_user }}"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/{{ zsh_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: "master"
    clone: true
