---
- name: Converge
  hosts: all
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  tasks:
    - include_role:
        name: "ansible-role-zsh"
