---
- name: Converge
  hosts: all
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  pre_tasks:
    - name: Ensure apt cache are updated
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    - name: Ensure dependencies are installed
      block:
        - name: Ensure iproute is installed
          package:
            name: iproute
            state: present
        - name: Gather ansible_default_ipv4 variable
          setup:
      when: ansible_os_family == "RedHat"
  tasks:
    - include_role:
        name: "ansible-role-zsh"
