name: CI
on:
  workflow_dispatch:
    inputs:
      runKics:
        description: Run KICS scan
        type: boolean
        default: true
      runLint:
        description: Run Ansible Lint
        type: boolean
        default: true
      runMolecule:
        description: Run Ansible Molecule
        type: boolean
        default: true
      publishRelease:
        description: Publish release
        type: boolean
        default: false
        required: false
  push:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  KICS_SCAN_PATH: "./"

jobs:
  #   scan:
  #     name: Checkmarx KICS
  #     runs-on: ubuntu-latest
  #     timeout-minutes: 5
  #     if: |
  #       inputs.runKics == true ||
  #       github.event_name == 'push' ||
  #       github.event_name == 'pull_request' ||
  #       github.event_name == 'schedule'
  #     permissions:
  #       contents: read # for actions/checkout to fetch code
  #       issues: write # for checkmarx/kics-github-action to write feedback to github issues
  #       pull-requests: write # for checkmarx/kics-github-action to write feedback to PR
  #       security-events: write # for github/codeql-action/upload-sarif to upload report for CodeQL/Security Alerts
  #       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  #     steps:
  #       - name: Harden Runner
  #         uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
  #         with:
  #           disable-sudo: true
  #           egress-policy: audit

  #       - name: Checkout
  #         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  #       - name: Run KICS scan
  #         uses: checkmarx/kics-github-action@8a44970e3d2eca668be41abe9d4e06709c3b3609 # v1.7.0
  #         with:
  #           path: ${{ env.KICS_SCAN_PATH }}
  #           fail_on: high
  #           output_formats: "json,sarif"
  #           exclude_paths: ".github/workflows/scorecard.yml"
  #         continue-on-error: true

  #       - name: Upload to code-scanning
  #         uses: github/codeql-action/upload-sarif@0b21cf2492b6b02c465a3e5d7c473717ad7721ba # v3.23.1
  #         with:
  #           sarif_file: results.sarif

  #   lint:
  #     name: Ansible Lint
  #     runs-on: ubuntu-latest
  #     timeout-minutes: 5
  #     if: |
  #       inputs.runLint == true ||
  #       github.event_name == 'push' ||
  #       github.event_name == 'pull_request' ||
  #       github.event_name == 'schedule'
  #     steps:
  #       - name: Harden Runner
  #         uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
  #         with:
  #           disable-sudo: true
  #           egress-policy: audit

  #       - name: Checkout
  #         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  #       - name: Run Ansible Lint
  #         uses: unleftie/ansible-lint-action@5e48b42dbdaef17c54c526b52776426f5819a818 # v1.0.3

  #   molecule:
  #     name: Ansible Molecule
  #     runs-on: ubuntu-latest
  #     timeout-minutes: 15
  #     if: |
  #       inputs.runMolecule == true ||
  #       github.event_name == 'push' ||
  #       github.event_name == 'pull_request' ||
  #       github.event_name == 'schedule'
  #     strategy:
  #       matrix:
  #         distro:
  #           - debian12

  #     steps:
  #       - name: Harden Runner
  #         uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
  #         with:
  #           disable-sudo: true
  #           egress-policy: audit

  #       - name: Checkout
  #         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  #       - name: Run Ansible Molecule
  #         uses: unleftie/ansible-molecule-action@22635a495dd572eb6cf70791f1af9a75979caf7d # v1.6.3
  #         with:
  #           github_token: ${{ secrets.GITHUB_TOKEN }}
  #           role_name: ${{ github.event.repository.name }}
  #           distro: ${{ matrix.distro }}

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: inputs.publishRelease == true || github.event_name == 'push'
    # needs: [scan, lint, molecule]
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18.0.0
          extra_plugins: conventional-changelog-conventionalcommits
