name: CI
on:
  workflow_dispatch:
    inputs:
      runKics:
        description: Run KICS scan
        type: boolean
        default: true
      runLint:
        description: Run Ansible Lint
        type: boolean
        default: true
      runMolecule:
        description: Run Ansible Molecule
        type: boolean
        default: true
  push:
    paths-ignore:
      - README.md
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  ACTIONS_REPOSITORY: "gha-templates"

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan:
    name: Checkmarx KICS
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      inputs.runKics == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'schedule'
    permissions:
      contents: read # for actions/checkout to fetch code
      issues: write # for checkmarx/kics-github-action to write feedback to github issues
      pull-requests: write # for checkmarx/kics-github-action to write feedback to PR
      security-events: write # for github/codeql-action/upload-sarif to upload report for CodeQL/Security Alerts
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout actions repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/${{ env.ACTIONS_REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gha_templates
          fetch-depth: 0

      - name: Run KICS scan
        uses: ./gha_templates/checkmarx-kics
        with:
          path: "tasks"

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      inputs.runLint == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'schedule'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout actions repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/${{ env.ACTIONS_REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gha_templates
          fetch-depth: 0

      - name: Run Ansible Lint
        uses: ./gha_templates/ansible-lint

  molecule:
    name: Ansible Molecule
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      inputs.runMolecule == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'schedule'
    strategy:
      matrix:
        distro:
          - debian12

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout actions repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/${{ env.ACTIONS_REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gha_templates
          fetch-depth: 0

      - name: Run Ansible Molecule
        uses: ./gha_templates/ansible-molecule
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          role_name: ${{ github.event.repository.name }}
          distro: ${{ matrix.distro }}
